### ISSUE TITLE
In serve mode, reload when dependencies change

### ISSUE THREAD

**Issue by binyamin** [binyamin/cedar#5]
## Summary
In serve mode, reload a file when one of its dependencies changes. This makes development much easier, and matches the behavior of many task-runners and static-site generators.

## Tasks
- [ ] examine & evaluate existing implementations
  - [PostCSS CLI](https://github.com/postcss/postcss-cli/blob/master/index.js) creates a dependency graph on the first run
- [ ] integrate solution with existing code
- [ ] add documentation, if necessary

## Notes
- Postcss lists dependencies in the result from the API call. See [the runner guidelines](https://github.com/postcss/postcss/blob/main/docs/guidelines/runner.md#31-rebuild-when-dependencies-change).
- esbuild has its own file watcher. It also can return a map of imports/dependencies (the [metafile](https://esbuild.github.io/api/#metafile))
- Nunjucks also has its own file watcher. I'm not sure if we can even get a dependency map from Nunjucks itself. It might be worth it to just let Nunjucks watch the files, and it will figure out whether something is a dependency.
